// <auto-generated />
using System;
using BoutiqueEnLigne.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoutiqueEnLigne.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251128153324_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BoutiqueEnLigne.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Produits électroniques",
                            Nom = "Électronique"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Articles vestimentaires",
                            Nom = "Vêtements"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Livres et magazines",
                            Nom = "Livres"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Articles pour la maison",
                            Nom = "Maison"
                        });
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Commande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresseLivraison")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodePostalLivraison")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontantTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroCommande")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatutCommande")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephoneLivraison")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.Property<string>("VilleLivraison")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.LigneCommande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommandeId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProduitId")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommandeId");

                    b.HasIndex("ProduitId");

                    b.ToTable("LignesCommande");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Panier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId")
                        .IsUnique();

                    b.ToTable("Paniers");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.PanierItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PanierId")
                        .HasColumnType("int");

                    b.Property<int>("ProduitId")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PanierId");

                    b.HasIndex("ProduitId");

                    b.ToTable("PaniersItems");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NombreVues")
                        .HasColumnType("int");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.ToTable("Produits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategorieId = 1,
                            DateAjout = new DateTime(2025, 11, 28, 16, 33, 24, 256, DateTimeKind.Local).AddTicks(8633),
                            Description = "Téléphone intelligent dernière génération",
                            ImageUrl = "/images/phone.jpg",
                            Nom = "Smartphone XYZ",
                            NombreVues = 0,
                            Prix = 599.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            CategorieId = 1,
                            DateAjout = new DateTime(2025, 11, 28, 16, 33, 24, 256, DateTimeKind.Local).AddTicks(8646),
                            Description = "PC portable performant",
                            ImageUrl = "/images/laptop.jpg",
                            Nom = "Ordinateur Portable",
                            NombreVues = 0,
                            Prix = 1299.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 3,
                            CategorieId = 2,
                            DateAjout = new DateTime(2025, 11, 28, 16, 33, 24, 256, DateTimeKind.Local).AddTicks(8648),
                            Description = "T-shirt 100% coton",
                            ImageUrl = "/images/tshirt.jpg",
                            Nom = "T-Shirt Coton",
                            NombreVues = 0,
                            Prix = 29.99m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 4,
                            CategorieId = 2,
                            DateAjout = new DateTime(2025, 11, 28, 16, 33, 24, 256, DateTimeKind.Local).AddTicks(8650),
                            Description = "Jean slim confortable",
                            ImageUrl = "/images/jeans.jpg",
                            Nom = "Jeans Slim",
                            NombreVues = 0,
                            Prix = 79.99m,
                            Stock = 75
                        },
                        new
                        {
                            Id = 5,
                            CategorieId = 3,
                            DateAjout = new DateTime(2025, 11, 28, 16, 33, 24, 256, DateTimeKind.Local).AddTicks(8651),
                            Description = "Le meilleur roman de l'année",
                            ImageUrl = "/images/book.jpg",
                            Nom = "Roman Bestseller",
                            NombreVues = 0,
                            Prix = 19.99m,
                            Stock = 200
                        });
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Commande", b =>
                {
                    b.HasOne("BoutiqueEnLigne.Models.Utilisateur", "Utilisateur")
                        .WithMany("Commandes")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.LigneCommande", b =>
                {
                    b.HasOne("BoutiqueEnLigne.Models.Commande", "Commande")
                        .WithMany("LignesCommande")
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoutiqueEnLigne.Models.Produit", "Produit")
                        .WithMany("LignesCommande")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Panier", b =>
                {
                    b.HasOne("BoutiqueEnLigne.Models.Utilisateur", "Utilisateur")
                        .WithOne("Panier")
                        .HasForeignKey("BoutiqueEnLigne.Models.Panier", "UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.PanierItem", b =>
                {
                    b.HasOne("BoutiqueEnLigne.Models.Panier", "Panier")
                        .WithMany("Items")
                        .HasForeignKey("PanierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoutiqueEnLigne.Models.Produit", "Produit")
                        .WithMany("PaniersItems")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Panier");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Produit", b =>
                {
                    b.HasOne("BoutiqueEnLigne.Models.Categorie", "Categorie")
                        .WithMany("Produits")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Categorie", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Commande", b =>
                {
                    b.Navigation("LignesCommande");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Panier", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Produit", b =>
                {
                    b.Navigation("LignesCommande");

                    b.Navigation("PaniersItems");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Utilisateur", b =>
                {
                    b.Navigation("Commandes");

                    b.Navigation("Panier")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
