// <auto-generated />
using System;
using BoutiqueEnLigne.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoutiqueEnLigne.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251129200308_AjoutCodesPromo")]
    partial class AjoutCodesPromo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BoutiqueEnLigne.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreation = new DateTime(2025, 11, 29, 21, 3, 8, 197, DateTimeKind.Local).AddTicks(7656),
                            Email = "admin@boutique.com",
                            MotDePasseHash = "$2a$11$8vJ3qXQZY.8XxZ9jC6L5Iu5nHZqGKxFQYXz0PZ7dH5QZdYxZNQqE2",
                            Nom = "Administrateur"
                        });
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Produits électroniques",
                            Nom = "Électronique"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Articles vestimentaires",
                            Nom = "Vêtements"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Livres et magazines",
                            Nom = "Livres"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Articles pour la maison",
                            Nom = "Maison"
                        });
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.CodePromo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MontantFixe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MontantMinimum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Pourcentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("UtilisationsActuelles")
                        .HasColumnType("int");

                    b.Property<int?>("UtilisationsMax")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CodesPromo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actif = true,
                            Code = "BIENVENUE10",
                            DateDebut = new DateTime(2025, 10, 30, 21, 3, 8, 197, DateTimeKind.Local).AddTicks(7846),
                            DateFin = new DateTime(2026, 5, 29, 21, 3, 8, 197, DateTimeKind.Local).AddTicks(7850),
                            Description = "10% de réduction pour les nouveaux clients",
                            MontantMinimum = 50m,
                            Pourcentage = 10m,
                            UtilisationsActuelles = 0,
                            UtilisationsMax = 100
                        },
                        new
                        {
                            Id = 2,
                            Actif = true,
                            Code = "PROMO5EUR",
                            DateDebut = new DateTime(2025, 11, 14, 21, 3, 8, 197, DateTimeKind.Local).AddTicks(7857),
                            DateFin = new DateTime(2026, 2, 28, 21, 3, 8, 197, DateTimeKind.Local).AddTicks(7858),
                            Description = "5€ de réduction",
                            MontantFixe = 5.00m,
                            MontantMinimum = 30m,
                            Pourcentage = 0m,
                            UtilisationsActuelles = 0,
                            UtilisationsMax = 50
                        },
                        new
                        {
                            Id = 3,
                            Actif = true,
                            Code = "MEGA20",
                            DateDebut = new DateTime(2025, 11, 29, 21, 3, 8, 197, DateTimeKind.Local).AddTicks(7860),
                            DateFin = new DateTime(2025, 12, 6, 21, 3, 8, 197, DateTimeKind.Local).AddTicks(7860),
                            Description = "20% de réduction - Offre limitée",
                            MontantMinimum = 100m,
                            Pourcentage = 20m,
                            UtilisationsActuelles = 0,
                            UtilisationsMax = 20
                        });
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Commande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresseLivraison")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodePostalLivraison")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodePromoUtilise")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontantReduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroCommande")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatutCommande")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephoneLivraison")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.Property<string>("VilleLivraison")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.LigneCommande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommandeId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProduitId")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommandeId");

                    b.HasIndex("ProduitId");

                    b.ToTable("LignesCommande");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Panier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId")
                        .IsUnique();

                    b.ToTable("Paniers");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.PanierItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PanierId")
                        .HasColumnType("int");

                    b.Property<int>("ProduitId")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PanierId");

                    b.HasIndex("ProduitId");

                    b.ToTable("PaniersItems");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NombreVues")
                        .HasColumnType("int");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.ToTable("Produits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategorieId = 1,
                            DateAjout = new DateTime(2025, 11, 29, 21, 3, 8, 197, DateTimeKind.Local).AddTicks(7593),
                            Description = "Téléphone intelligent dernière génération avec écran OLED 6.5 pouces, 128GB",
                            ImageUrl = "/images/produits/phone.jpg",
                            Nom = "Smartphone XYZ",
                            NombreVues = 0,
                            Prix = 599.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            CategorieId = 1,
                            DateAjout = new DateTime(2025, 11, 29, 21, 3, 8, 197, DateTimeKind.Local).AddTicks(7603),
                            Description = "PC portable performant 15 pouces, Intel i7, 16GB RAM, SSD 512GB",
                            ImageUrl = "/images/produits/laptop.jpg",
                            Nom = "Ordinateur Portable Pro",
                            NombreVues = 0,
                            Prix = 1299.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 6,
                            CategorieId = 1,
                            DateAjout = new DateTime(2025, 11, 29, 21, 3, 8, 197, DateTimeKind.Local).AddTicks(7605),
                            Description = "Casque sans fil avec réduction de bruit active, autonomie 30h",
                            ImageUrl = "/images/produits/headphones.jpg",
                            Nom = "Casque Audio Bluetooth",
                            NombreVues = 0,
                            Prix = 149.99m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 7,
                            CategorieId = 1,
                            DateAjout = new DateTime(2025, 11, 29, 21, 3, 8, 197, DateTimeKind.Local).AddTicks(7607),
                            Description = "Tablette Android haute performance, écran Full HD",
                            ImageUrl = "/images/produits/tablet.jpg",
                            Nom = "Tablette 10 pouces",
                            NombreVues = 0,
                            Prix = 299.99m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 8,
                            CategorieId = 1,
                            DateAjout = new DateTime(2025, 11, 29, 21, 3, 8, 197, DateTimeKind.Local).AddTicks(7608),
                            Description = "Smartwatch avec suivi santé, GPS, notifications smartphone",
                            ImageUrl = "/images/produits/smartwatch.jpg",
                            Nom = "Montre Connectée",
                            NombreVues = 0,
                            Prix = 199.99m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 3,
                            CategorieId = 2,
                            DateAjout = new DateTime(2025, 11, 29, 21, 3, 8, 197, DateTimeKind.Local).AddTicks(7610),
                            Description = "T-shirt 100% coton bio, coupe moderne",
                            ImageUrl = "/images/produits/tshirt.jpg",
                            Nom = "T-Shirt Coton Premium",
                            NombreVues = 0,
                            Prix = 29.99m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 4,
                            CategorieId = 2,
                            DateAjout = new DateTime(2025, 11, 29, 21, 3, 8, 197, DateTimeKind.Local).AddTicks(7611),
                            Description = "Jean slim confortable en denim stretch",
                            ImageUrl = "/images/produits/jeans.jpg",
                            Nom = "Jeans Slim Fit",
                            NombreVues = 0,
                            Prix = 79.99m,
                            Stock = 75
                        },
                        new
                        {
                            Id = 9,
                            CategorieId = 2,
                            DateAjout = new DateTime(2025, 11, 29, 21, 3, 8, 197, DateTimeKind.Local).AddTicks(7613),
                            Description = "Chemise coton égyptien, coupe cintrée",
                            ImageUrl = "/images/produits/shirt.jpg",
                            Nom = "Chemise Homme Élégante",
                            NombreVues = 0,
                            Prix = 49.99m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 10,
                            CategorieId = 2,
                            DateAjout = new DateTime(2025, 11, 29, 21, 3, 8, 197, DateTimeKind.Local).AddTicks(7614),
                            Description = "Robe légère et élégante, parfaite pour l'été",
                            ImageUrl = "/images/produits/dress.jpg",
                            Nom = "Robe d'Été Femme",
                            NombreVues = 0,
                            Prix = 69.99m,
                            Stock = 55
                        },
                        new
                        {
                            Id = 11,
                            CategorieId = 2,
                            DateAjout = new DateTime(2025, 11, 29, 21, 3, 8, 197, DateTimeKind.Local).AddTicks(7616),
                            Description = "Veste en cuir véritable, style moderne",
                            ImageUrl = "/images/produits/jacket.jpg",
                            Nom = "Veste en Cuir",
                            NombreVues = 0,
                            Prix = 249.99m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 5,
                            CategorieId = 3,
                            DateAjout = new DateTime(2025, 11, 29, 21, 3, 8, 197, DateTimeKind.Local).AddTicks(7617),
                            Description = "Le meilleur roman de l'année, histoire captivante",
                            ImageUrl = "/images/produits/book1.jpg",
                            Nom = "Roman Bestseller 2024",
                            NombreVues = 0,
                            Prix = 19.99m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 12,
                            CategorieId = 3,
                            DateAjout = new DateTime(2025, 11, 29, 21, 3, 8, 197, DateTimeKind.Local).AddTicks(7619),
                            Description = "Livre complet pour apprendre C# et .NET",
                            ImageUrl = "/images/produits/book2.jpg",
                            Nom = "Guide Programmation C#",
                            NombreVues = 0,
                            Prix = 45.99m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 13,
                            CategorieId = 3,
                            DateAjout = new DateTime(2025, 11, 29, 21, 3, 8, 197, DateTimeKind.Local).AddTicks(7620),
                            Description = "Saga épique en 3 tomes, monde imaginaire",
                            ImageUrl = "/images/produits/book3.jpg",
                            Nom = "Roman Fantastique",
                            NombreVues = 0,
                            Prix = 24.99m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 14,
                            CategorieId = 3,
                            DateAjout = new DateTime(2025, 11, 29, 21, 3, 8, 197, DateTimeKind.Local).AddTicks(7621),
                            Description = "Magazine mensuel sur les nouvelles technologies",
                            ImageUrl = "/images/produits/magazine.jpg",
                            Nom = "Magazine Tech Monthly",
                            NombreVues = 0,
                            Prix = 9.99m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 15,
                            CategorieId = 4,
                            DateAjout = new DateTime(2025, 11, 29, 21, 3, 8, 197, DateTimeKind.Local).AddTicks(7623),
                            Description = "Lampe moderne avec intensité réglable",
                            ImageUrl = "/images/produits/lamp.jpg",
                            Nom = "Lampe de Bureau LED",
                            NombreVues = 0,
                            Prix = 39.99m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 16,
                            CategorieId = 4,
                            DateAjout = new DateTime(2025, 11, 29, 21, 3, 8, 197, DateTimeKind.Local).AddTicks(7624),
                            Description = "Coussin moelleux en velours, plusieurs couleurs",
                            ImageUrl = "/images/produits/pillow.jpg",
                            Nom = "Coussin Décoratif",
                            NombreVues = 0,
                            Prix = 24.99m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 17,
                            CategorieId = 4,
                            DateAjout = new DateTime(2025, 11, 29, 21, 3, 8, 197, DateTimeKind.Local).AddTicks(7626),
                            Description = "Ensemble d'ustensiles en acier inoxydable",
                            ImageUrl = "/images/produits/kitchen.jpg",
                            Nom = "Set Cuisine 12 Pièces",
                            NombreVues = 0,
                            Prix = 89.99m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 18,
                            CategorieId = 4,
                            DateAjout = new DateTime(2025, 11, 29, 21, 3, 8, 197, DateTimeKind.Local).AddTicks(7627),
                            Description = "Tapis moderne et confortable",
                            ImageUrl = "/images/produits/carpet.jpg",
                            Nom = "Tapis Salon 160x230cm",
                            NombreVues = 0,
                            Prix = 129.99m,
                            Stock = 20
                        });
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Commande", b =>
                {
                    b.HasOne("BoutiqueEnLigne.Models.Utilisateur", "Utilisateur")
                        .WithMany("Commandes")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.LigneCommande", b =>
                {
                    b.HasOne("BoutiqueEnLigne.Models.Commande", "Commande")
                        .WithMany("LignesCommande")
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoutiqueEnLigne.Models.Produit", "Produit")
                        .WithMany("LignesCommande")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Panier", b =>
                {
                    b.HasOne("BoutiqueEnLigne.Models.Utilisateur", "Utilisateur")
                        .WithOne("Panier")
                        .HasForeignKey("BoutiqueEnLigne.Models.Panier", "UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.PanierItem", b =>
                {
                    b.HasOne("BoutiqueEnLigne.Models.Panier", "Panier")
                        .WithMany("Items")
                        .HasForeignKey("PanierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoutiqueEnLigne.Models.Produit", "Produit")
                        .WithMany("PaniersItems")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Panier");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Produit", b =>
                {
                    b.HasOne("BoutiqueEnLigne.Models.Categorie", "Categorie")
                        .WithMany("Produits")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Categorie", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Commande", b =>
                {
                    b.Navigation("LignesCommande");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Panier", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Produit", b =>
                {
                    b.Navigation("LignesCommande");

                    b.Navigation("PaniersItems");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Utilisateur", b =>
                {
                    b.Navigation("Commandes");

                    b.Navigation("Panier")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
