// <auto-generated />
using System;
using BoutiqueEnLigne.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoutiqueEnLigne.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BoutiqueEnLigne.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreation = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@boutique.com",
                            MotDePasseHash = "$2a$11$t/wPvspnjv8dRdnLglwYLucujuYK/yB4kDTlVuFBX8c7TifoPGOxa",
                            Nom = "Administrateur"
                        });
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.AttributCategorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.Property<string>("NomAttribut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeAttribut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValeursDisponibles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.ToTable("AttributsCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategorieId = 2,
                            NomAttribut = "Taille",
                            TypeAttribut = "select",
                            ValeursDisponibles = "XS,S,M,L,XL,XXL"
                        },
                        new
                        {
                            Id = 2,
                            CategorieId = 2,
                            NomAttribut = "Couleur",
                            TypeAttribut = "select",
                            ValeursDisponibles = "Noir,Blanc,Bleu,Rouge,Vert,Gris,Rose,Jaune"
                        },
                        new
                        {
                            Id = 3,
                            CategorieId = 2,
                            NomAttribut = "Genre",
                            TypeAttribut = "select",
                            ValeursDisponibles = "Homme,Femme,Unisexe"
                        },
                        new
                        {
                            Id = 4,
                            CategorieId = 2,
                            NomAttribut = "Matière",
                            TypeAttribut = "select",
                            ValeursDisponibles = "Coton,Polyester,Laine,Jean,Cuir,Soie"
                        },
                        new
                        {
                            Id = 5,
                            CategorieId = 1,
                            NomAttribut = "Marque",
                            TypeAttribut = "select",
                            ValeursDisponibles = "Samsung,Apple,Sony,LG,Xiaomi,Huawei,HP,Dell"
                        },
                        new
                        {
                            Id = 6,
                            CategorieId = 1,
                            NomAttribut = "Stockage",
                            TypeAttribut = "select",
                            ValeursDisponibles = "32GB,64GB,128GB,256GB,512GB,1TB"
                        },
                        new
                        {
                            Id = 7,
                            CategorieId = 1,
                            NomAttribut = "Couleur",
                            TypeAttribut = "select",
                            ValeursDisponibles = "Noir,Blanc,Bleu,Argent,Or,Rouge"
                        },
                        new
                        {
                            Id = 8,
                            CategorieId = 3,
                            NomAttribut = "Format",
                            TypeAttribut = "select",
                            ValeursDisponibles = "Broché,Relié,Poche,Ebook"
                        },
                        new
                        {
                            Id = 9,
                            CategorieId = 3,
                            NomAttribut = "Langue",
                            TypeAttribut = "select",
                            ValeursDisponibles = "Français,Anglais,Arabe,Espagnol"
                        },
                        new
                        {
                            Id = 10,
                            CategorieId = 3,
                            NomAttribut = "Genre",
                            TypeAttribut = "select",
                            ValeursDisponibles = "Roman,Science-Fiction,Thriller,Biographie,Technique,Jeunesse"
                        },
                        new
                        {
                            Id = 11,
                            CategorieId = 4,
                            NomAttribut = "Matériau",
                            TypeAttribut = "select",
                            ValeursDisponibles = "Bois,Métal,Plastique,Verre,Tissu"
                        },
                        new
                        {
                            Id = 12,
                            CategorieId = 4,
                            NomAttribut = "Couleur",
                            TypeAttribut = "select",
                            ValeursDisponibles = "Blanc,Noir,Beige,Gris,Bleu,Rouge,Vert"
                        },
                        new
                        {
                            Id = 13,
                            CategorieId = 4,
                            NomAttribut = "Dimensions",
                            TypeAttribut = "select",
                            ValeursDisponibles = "Petit,Moyen,Grand,XL"
                        },
                        new
                        {
                            Id = 14,
                            CategorieId = 5,
                            NomAttribut = "Pointure",
                            TypeAttribut = "select",
                            ValeursDisponibles = "35,36,37,38,39,40,41,42,43,44,45,46"
                        },
                        new
                        {
                            Id = 15,
                            CategorieId = 5,
                            NomAttribut = "Genre",
                            TypeAttribut = "select",
                            ValeursDisponibles = "Homme,Femme,Enfant,Unisexe"
                        },
                        new
                        {
                            Id = 16,
                            CategorieId = 5,
                            NomAttribut = "Type",
                            TypeAttribut = "select",
                            ValeursDisponibles = "Sneakers,Bottes,Sandales,Escarpins,Mocassins,Baskets,Chaussures de sport"
                        },
                        new
                        {
                            Id = 17,
                            CategorieId = 5,
                            NomAttribut = "Couleur",
                            TypeAttribut = "select",
                            ValeursDisponibles = "Noir,Blanc,Marron,Bleu,Rouge,Beige,Gris,Rose"
                        },
                        new
                        {
                            Id = 18,
                            CategorieId = 5,
                            NomAttribut = "Matière",
                            TypeAttribut = "select",
                            ValeursDisponibles = "Cuir,Tissu,Synthétique,Daim,Toile"
                        },
                        new
                        {
                            Id = 19,
                            CategorieId = 6,
                            NomAttribut = "Famille Olfactive",
                            TypeAttribut = "select",
                            ValeursDisponibles = "Floral,Oriental,Boisé,Frais,Fruité,Épicé,Ambré"
                        },
                        new
                        {
                            Id = 20,
                            CategorieId = 6,
                            NomAttribut = "Genre",
                            TypeAttribut = "select",
                            ValeursDisponibles = "Homme,Femme,Mixte"
                        },
                        new
                        {
                            Id = 21,
                            CategorieId = 6,
                            NomAttribut = "Concentration",
                            TypeAttribut = "select",
                            ValeursDisponibles = "Eau de Toilette,Eau de Parfum,Parfum,Cologne"
                        },
                        new
                        {
                            Id = 22,
                            CategorieId = 6,
                            NomAttribut = "Volume",
                            TypeAttribut = "select",
                            ValeursDisponibles = "30ml,50ml,75ml,100ml,150ml"
                        },
                        new
                        {
                            Id = 23,
                            CategorieId = 6,
                            NomAttribut = "Marque",
                            TypeAttribut = "select",
                            ValeursDisponibles = "Chanel,Dior,Gucci,Yves Saint Laurent,Calvin Klein,Hugo Boss,Paco Rabanne,Armani"
                        },
                        new
                        {
                            Id = 24,
                            CategorieId = 6,
                            NomAttribut = "Intensité",
                            TypeAttribut = "select",
                            ValeursDisponibles = "Légère,Moyenne,Forte,Très Forte"
                        });
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.AttributProduit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomAttribut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProduitId")
                        .HasColumnType("int");

                    b.Property<string>("ValeurAttribut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProduitId");

                    b.ToTable("AttributsProduits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomAttribut = "Taille",
                            ProduitId = 3,
                            ValeurAttribut = "S,M,L,XL"
                        },
                        new
                        {
                            Id = 2,
                            NomAttribut = "Couleur",
                            ProduitId = 3,
                            ValeurAttribut = "Noir,Blanc,Bleu"
                        },
                        new
                        {
                            Id = 3,
                            NomAttribut = "Genre",
                            ProduitId = 3,
                            ValeurAttribut = "Unisexe"
                        },
                        new
                        {
                            Id = 4,
                            NomAttribut = "Matière",
                            ProduitId = 3,
                            ValeurAttribut = "Coton"
                        },
                        new
                        {
                            Id = 5,
                            NomAttribut = "Taille",
                            ProduitId = 4,
                            ValeurAttribut = "30,32,34,36,38,40"
                        },
                        new
                        {
                            Id = 6,
                            NomAttribut = "Couleur",
                            ProduitId = 4,
                            ValeurAttribut = "Bleu,Noir"
                        },
                        new
                        {
                            Id = 7,
                            NomAttribut = "Genre",
                            ProduitId = 4,
                            ValeurAttribut = "Homme"
                        },
                        new
                        {
                            Id = 8,
                            NomAttribut = "Matière",
                            ProduitId = 4,
                            ValeurAttribut = "Jean"
                        },
                        new
                        {
                            Id = 9,
                            NomAttribut = "Marque",
                            ProduitId = 1,
                            ValeurAttribut = "Samsung"
                        },
                        new
                        {
                            Id = 10,
                            NomAttribut = "Stockage",
                            ProduitId = 1,
                            ValeurAttribut = "128GB"
                        },
                        new
                        {
                            Id = 11,
                            NomAttribut = "Couleur",
                            ProduitId = 1,
                            ValeurAttribut = "Noir,Blanc,Bleu"
                        },
                        new
                        {
                            Id = 12,
                            NomAttribut = "Marque",
                            ProduitId = 2,
                            ValeurAttribut = "Apple"
                        },
                        new
                        {
                            Id = 13,
                            NomAttribut = "Stockage",
                            ProduitId = 2,
                            ValeurAttribut = "512GB"
                        },
                        new
                        {
                            Id = 14,
                            NomAttribut = "Couleur",
                            ProduitId = 2,
                            ValeurAttribut = "Argent,Gris"
                        },
                        new
                        {
                            Id = 15,
                            NomAttribut = "Format",
                            ProduitId = 5,
                            ValeurAttribut = "Broché"
                        },
                        new
                        {
                            Id = 16,
                            NomAttribut = "Langue",
                            ProduitId = 5,
                            ValeurAttribut = "Français"
                        },
                        new
                        {
                            Id = 17,
                            NomAttribut = "Genre",
                            ProduitId = 5,
                            ValeurAttribut = "Roman"
                        },
                        new
                        {
                            Id = 18,
                            NomAttribut = "Pointure",
                            ProduitId = 29,
                            ValeurAttribut = "39,40,41,42,43,44"
                        },
                        new
                        {
                            Id = 19,
                            NomAttribut = "Genre",
                            ProduitId = 29,
                            ValeurAttribut = "Unisexe"
                        },
                        new
                        {
                            Id = 20,
                            NomAttribut = "Type",
                            ProduitId = 29,
                            ValeurAttribut = "Baskets"
                        },
                        new
                        {
                            Id = 21,
                            NomAttribut = "Couleur",
                            ProduitId = 29,
                            ValeurAttribut = "Noir,Blanc,Bleu"
                        },
                        new
                        {
                            Id = 22,
                            NomAttribut = "Matière",
                            ProduitId = 29,
                            ValeurAttribut = "Tissu"
                        },
                        new
                        {
                            Id = 23,
                            NomAttribut = "Pointure",
                            ProduitId = 30,
                            ValeurAttribut = "40,41,42,43,44,45"
                        },
                        new
                        {
                            Id = 24,
                            NomAttribut = "Genre",
                            ProduitId = 30,
                            ValeurAttribut = "Homme"
                        },
                        new
                        {
                            Id = 25,
                            NomAttribut = "Type",
                            ProduitId = 30,
                            ValeurAttribut = "Bottes"
                        },
                        new
                        {
                            Id = 26,
                            NomAttribut = "Couleur",
                            ProduitId = 30,
                            ValeurAttribut = "Marron,Noir"
                        },
                        new
                        {
                            Id = 27,
                            NomAttribut = "Matière",
                            ProduitId = 30,
                            ValeurAttribut = "Cuir"
                        },
                        new
                        {
                            Id = 28,
                            NomAttribut = "Pointure",
                            ProduitId = 31,
                            ValeurAttribut = "36,37,38,39,40,41"
                        },
                        new
                        {
                            Id = 29,
                            NomAttribut = "Genre",
                            ProduitId = 31,
                            ValeurAttribut = "Femme"
                        },
                        new
                        {
                            Id = 30,
                            NomAttribut = "Type",
                            ProduitId = 31,
                            ValeurAttribut = "Sandales"
                        },
                        new
                        {
                            Id = 31,
                            NomAttribut = "Couleur",
                            ProduitId = 31,
                            ValeurAttribut = "Beige,Rose,Blanc"
                        },
                        new
                        {
                            Id = 32,
                            NomAttribut = "Matière",
                            ProduitId = 31,
                            ValeurAttribut = "Synthétique"
                        },
                        new
                        {
                            Id = 33,
                            NomAttribut = "Pointure",
                            ProduitId = 32,
                            ValeurAttribut = "36,37,38,39,40"
                        },
                        new
                        {
                            Id = 34,
                            NomAttribut = "Genre",
                            ProduitId = 32,
                            ValeurAttribut = "Femme"
                        },
                        new
                        {
                            Id = 35,
                            NomAttribut = "Type",
                            ProduitId = 32,
                            ValeurAttribut = "Escarpins"
                        },
                        new
                        {
                            Id = 36,
                            NomAttribut = "Couleur",
                            ProduitId = 32,
                            ValeurAttribut = "Noir"
                        },
                        new
                        {
                            Id = 37,
                            NomAttribut = "Matière",
                            ProduitId = 32,
                            ValeurAttribut = "Cuir"
                        },
                        new
                        {
                            Id = 38,
                            NomAttribut = "Pointure",
                            ProduitId = 33,
                            ValeurAttribut = "38,39,40,41,42,43"
                        },
                        new
                        {
                            Id = 39,
                            NomAttribut = "Genre",
                            ProduitId = 33,
                            ValeurAttribut = "Unisexe"
                        },
                        new
                        {
                            Id = 40,
                            NomAttribut = "Type",
                            ProduitId = 33,
                            ValeurAttribut = "Sneakers"
                        },
                        new
                        {
                            Id = 41,
                            NomAttribut = "Couleur",
                            ProduitId = 33,
                            ValeurAttribut = "Blanc,Noir"
                        },
                        new
                        {
                            Id = 42,
                            NomAttribut = "Matière",
                            ProduitId = 33,
                            ValeurAttribut = "Toile"
                        },
                        new
                        {
                            Id = 43,
                            NomAttribut = "Famille Olfactive",
                            ProduitId = 34,
                            ValeurAttribut = "Floral"
                        },
                        new
                        {
                            Id = 44,
                            NomAttribut = "Genre",
                            ProduitId = 34,
                            ValeurAttribut = "Femme"
                        },
                        new
                        {
                            Id = 45,
                            NomAttribut = "Concentration",
                            ProduitId = 34,
                            ValeurAttribut = "Eau de Parfum"
                        },
                        new
                        {
                            Id = 46,
                            NomAttribut = "Volume",
                            ProduitId = 34,
                            ValeurAttribut = "100ml"
                        },
                        new
                        {
                            Id = 47,
                            NomAttribut = "Marque",
                            ProduitId = 34,
                            ValeurAttribut = "Chanel"
                        },
                        new
                        {
                            Id = 48,
                            NomAttribut = "Intensité",
                            ProduitId = 34,
                            ValeurAttribut = "Forte"
                        },
                        new
                        {
                            Id = 49,
                            NomAttribut = "Famille Olfactive",
                            ProduitId = 35,
                            ValeurAttribut = "Frais"
                        },
                        new
                        {
                            Id = 50,
                            NomAttribut = "Genre",
                            ProduitId = 35,
                            ValeurAttribut = "Homme"
                        },
                        new
                        {
                            Id = 51,
                            NomAttribut = "Concentration",
                            ProduitId = 35,
                            ValeurAttribut = "Eau de Toilette"
                        },
                        new
                        {
                            Id = 52,
                            NomAttribut = "Volume",
                            ProduitId = 35,
                            ValeurAttribut = "100ml"
                        },
                        new
                        {
                            Id = 53,
                            NomAttribut = "Marque",
                            ProduitId = 35,
                            ValeurAttribut = "Dior"
                        },
                        new
                        {
                            Id = 54,
                            NomAttribut = "Intensité",
                            ProduitId = 35,
                            ValeurAttribut = "Moyenne"
                        },
                        new
                        {
                            Id = 55,
                            NomAttribut = "Famille Olfactive",
                            ProduitId = 36,
                            ValeurAttribut = "Oriental"
                        },
                        new
                        {
                            Id = 56,
                            NomAttribut = "Genre",
                            ProduitId = 36,
                            ValeurAttribut = "Femme"
                        },
                        new
                        {
                            Id = 57,
                            NomAttribut = "Concentration",
                            ProduitId = 36,
                            ValeurAttribut = "Eau de Parfum"
                        },
                        new
                        {
                            Id = 58,
                            NomAttribut = "Volume",
                            ProduitId = 36,
                            ValeurAttribut = "50ml,90ml"
                        },
                        new
                        {
                            Id = 59,
                            NomAttribut = "Marque",
                            ProduitId = 36,
                            ValeurAttribut = "Yves Saint Laurent"
                        },
                        new
                        {
                            Id = 60,
                            NomAttribut = "Intensité",
                            ProduitId = 36,
                            ValeurAttribut = "Très Forte"
                        },
                        new
                        {
                            Id = 61,
                            NomAttribut = "Famille Olfactive",
                            ProduitId = 37,
                            ValeurAttribut = "Frais"
                        },
                        new
                        {
                            Id = 62,
                            NomAttribut = "Genre",
                            ProduitId = 37,
                            ValeurAttribut = "Homme"
                        },
                        new
                        {
                            Id = 63,
                            NomAttribut = "Concentration",
                            ProduitId = 37,
                            ValeurAttribut = "Eau de Toilette"
                        },
                        new
                        {
                            Id = 64,
                            NomAttribut = "Volume",
                            ProduitId = 37,
                            ValeurAttribut = "75ml,100ml"
                        },
                        new
                        {
                            Id = 65,
                            NomAttribut = "Marque",
                            ProduitId = 37,
                            ValeurAttribut = "Armani"
                        },
                        new
                        {
                            Id = 66,
                            NomAttribut = "Intensité",
                            ProduitId = 37,
                            ValeurAttribut = "Légère"
                        },
                        new
                        {
                            Id = 67,
                            NomAttribut = "Famille Olfactive",
                            ProduitId = 38,
                            ValeurAttribut = "Floral"
                        },
                        new
                        {
                            Id = 68,
                            NomAttribut = "Genre",
                            ProduitId = 38,
                            ValeurAttribut = "Femme"
                        },
                        new
                        {
                            Id = 69,
                            NomAttribut = "Concentration",
                            ProduitId = 38,
                            ValeurAttribut = "Eau de Parfum"
                        },
                        new
                        {
                            Id = 70,
                            NomAttribut = "Volume",
                            ProduitId = 38,
                            ValeurAttribut = "50ml,100ml"
                        },
                        new
                        {
                            Id = 71,
                            NomAttribut = "Marque",
                            ProduitId = 38,
                            ValeurAttribut = "Yves Saint Laurent"
                        },
                        new
                        {
                            Id = 72,
                            NomAttribut = "Intensité",
                            ProduitId = 38,
                            ValeurAttribut = "Forte"
                        });
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Produits électroniques",
                            Nom = "Électronique"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Articles vestimentaires",
                            Nom = "Vêtements"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Livres et magazines",
                            Nom = "Livres"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Articles pour la maison",
                            Nom = "Maison"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Chaussures pour tous",
                            Nom = "Chaussures"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Parfums et fragrances",
                            Nom = "Parfums"
                        });
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.CodePromo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MontantFixe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MontantMinimum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Pourcentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("UtilisationsActuelles")
                        .HasColumnType("int");

                    b.Property<int?>("UtilisationsMax")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CodesPromo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actif = true,
                            Code = "BIENVENUE10",
                            DateDebut = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "10% de réduction pour les nouveaux clients",
                            MontantMinimum = 50m,
                            Pourcentage = 10m,
                            UtilisationsActuelles = 0,
                            UtilisationsMax = 100
                        },
                        new
                        {
                            Id = 2,
                            Actif = true,
                            Code = "PROMO5EUR",
                            DateDebut = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2024, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "5€ de réduction",
                            MontantFixe = 5.00m,
                            MontantMinimum = 30m,
                            Pourcentage = 0m,
                            UtilisationsActuelles = 0,
                            UtilisationsMax = 50
                        },
                        new
                        {
                            Id = 3,
                            Actif = true,
                            Code = "MEGA20",
                            DateDebut = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "20% de réduction - Offre limitée",
                            MontantMinimum = 100m,
                            Pourcentage = 20m,
                            UtilisationsActuelles = 0,
                            UtilisationsMax = 20
                        });
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Commande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresseLivraison")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodePostalLivraison")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodePromoUtilise")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontantReduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroCommande")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatutCommande")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephoneLivraison")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.Property<string>("VilleLivraison")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.LigneCommande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommandeId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProduitId")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommandeId");

                    b.HasIndex("ProduitId");

                    b.ToTable("LignesCommande");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Panier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId")
                        .IsUnique();

                    b.ToTable("Paniers");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.PanierItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PanierId")
                        .HasColumnType("int");

                    b.Property<int>("ProduitId")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PanierId");

                    b.HasIndex("ProduitId");

                    b.ToTable("PaniersItems");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NombreVues")
                        .HasColumnType("int");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.ToTable("Produits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategorieId = 1,
                            DateAjout = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Téléphone intelligent dernière génération avec écran OLED 6.5 pouces, 128GB",
                            ImageUrl = "/images/produits/phone.jpg",
                            Nom = "Smartphone XYZ",
                            NombreVues = 0,
                            Prix = 599.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            CategorieId = 1,
                            DateAjout = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "PC portable performant 15 pouces, Intel i7, 16GB RAM, SSD 512GB",
                            ImageUrl = "/images/produits/laptop.jpg",
                            Nom = "Ordinateur Portable Pro",
                            NombreVues = 0,
                            Prix = 1299.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 6,
                            CategorieId = 1,
                            DateAjout = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Casque sans fil avec réduction de bruit active, autonomie 30h",
                            ImageUrl = "/images/produits/headphones.jpg",
                            Nom = "Casque Audio Bluetooth",
                            NombreVues = 0,
                            Prix = 149.99m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 7,
                            CategorieId = 1,
                            DateAjout = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tablette Android haute performance, écran Full HD",
                            ImageUrl = "/images/produits/tablet.jpg",
                            Nom = "Tablette 10 pouces",
                            NombreVues = 0,
                            Prix = 299.99m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 8,
                            CategorieId = 1,
                            DateAjout = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Smartwatch avec suivi santé, GPS, notifications smartphone",
                            ImageUrl = "/images/produits/smartwatch.jpg",
                            Nom = "Montre Connectée",
                            NombreVues = 0,
                            Prix = 199.99m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 3,
                            CategorieId = 2,
                            DateAjout = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "T-shirt 100% coton bio, coupe moderne",
                            ImageUrl = "/images/produits/tshirt.jpg",
                            Nom = "T-Shirt Coton Premium",
                            NombreVues = 0,
                            Prix = 29.99m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 4,
                            CategorieId = 2,
                            DateAjout = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Jean slim confortable en denim stretch",
                            ImageUrl = "/images/produits/jeans.jpg",
                            Nom = "Jeans Slim Fit",
                            NombreVues = 0,
                            Prix = 79.99m,
                            Stock = 75
                        },
                        new
                        {
                            Id = 9,
                            CategorieId = 2,
                            DateAjout = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chemise coton égyptien, coupe cintrée",
                            ImageUrl = "/images/produits/shirt.jpg",
                            Nom = "Chemise Homme Élégante",
                            NombreVues = 0,
                            Prix = 49.99m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 10,
                            CategorieId = 2,
                            DateAjout = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Robe légère et élégante, parfaite pour l'été",
                            ImageUrl = "/images/produits/dress.jpg",
                            Nom = "Robe d'Été Femme",
                            NombreVues = 0,
                            Prix = 69.99m,
                            Stock = 55
                        },
                        new
                        {
                            Id = 11,
                            CategorieId = 2,
                            DateAjout = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Veste en cuir véritable, style moderne",
                            ImageUrl = "/images/produits/jacket.jpg",
                            Nom = "Veste en Cuir",
                            NombreVues = 0,
                            Prix = 249.99m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 5,
                            CategorieId = 3,
                            DateAjout = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Le meilleur roman de l'année, histoire captivante",
                            ImageUrl = "/images/produits/book1.jpg",
                            Nom = "Roman Bestseller 2024",
                            NombreVues = 0,
                            Prix = 19.99m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 12,
                            CategorieId = 3,
                            DateAjout = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Livre complet pour apprendre C# et .NET",
                            ImageUrl = "/images/produits/book2.jpg",
                            Nom = "Guide Programmation C#",
                            NombreVues = 0,
                            Prix = 45.99m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 13,
                            CategorieId = 3,
                            DateAjout = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Saga épique en 3 tomes, monde imaginaire",
                            ImageUrl = "/images/produits/book3.jpg",
                            Nom = "Roman Fantastique",
                            NombreVues = 0,
                            Prix = 24.99m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 14,
                            CategorieId = 3,
                            DateAjout = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Magazine mensuel sur les nouvelles technologies",
                            ImageUrl = "/images/produits/magazine.jpg",
                            Nom = "Magazine Tech Monthly",
                            NombreVues = 0,
                            Prix = 9.99m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 15,
                            CategorieId = 4,
                            DateAjout = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lampe moderne avec intensité réglable",
                            ImageUrl = "/images/produits/lamp.jpg",
                            Nom = "Lampe de Bureau LED",
                            NombreVues = 0,
                            Prix = 39.99m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 16,
                            CategorieId = 4,
                            DateAjout = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Coussin moelleux en velours, plusieurs couleurs",
                            ImageUrl = "/images/produits/pillow.jpg",
                            Nom = "Coussin Décoratif",
                            NombreVues = 0,
                            Prix = 24.99m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 17,
                            CategorieId = 4,
                            DateAjout = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ensemble d'ustensiles en acier inoxydable",
                            ImageUrl = "/images/produits/kitchen.jpg",
                            Nom = "Set Cuisine 12 Pièces",
                            NombreVues = 0,
                            Prix = 89.99m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 18,
                            CategorieId = 4,
                            DateAjout = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tapis moderne et confortable",
                            ImageUrl = "/images/produits/carpet.jpg",
                            Nom = "Tapis Salon 160x230cm",
                            NombreVues = 0,
                            Prix = 129.99m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 29,
                            CategorieId = 5,
                            DateAjout = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Baskets sportives confortables avec amorti Air Max, idéales pour le running",
                            ImageUrl = "/images/produits/sneakers.jpg",
                            Nom = "Nike Air Max 270",
                            NombreVues = 0,
                            Prix = 149.99m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 30,
                            CategorieId = 5,
                            DateAjout = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bottes élégantes en cuir véritable, parfaites pour l'automne",
                            ImageUrl = "/images/produits/boots.jpg",
                            Nom = "Bottes en Cuir Chelsea",
                            NombreVues = 0,
                            Prix = 179.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 31,
                            CategorieId = 5,
                            DateAjout = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sandales légères et confortables pour la plage",
                            ImageUrl = "/images/produits/sandals.jpg",
                            Nom = "Sandales d'Été",
                            NombreVues = 0,
                            Prix = 39.99m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 32,
                            CategorieId = 5,
                            DateAjout = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chaussures à talon pour occasions spéciales",
                            ImageUrl = "/images/produits/heels.jpg",
                            Nom = "Escarpins Noirs Élégants",
                            NombreVues = 0,
                            Prix = 89.99m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 33,
                            CategorieId = 5,
                            DateAjout = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sneakers style urbain avec semelle épaisse",
                            ImageUrl = "/images/produits/high-tops.jpg",
                            Nom = "Baskets Montantes",
                            NombreVues = 0,
                            Prix = 119.99m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 34,
                            CategorieId = 6,
                            DateAjout = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Parfum iconique aux notes florales et aldéhydées, intemporel et élégant",
                            ImageUrl = "/images/produits/chanel.jpg",
                            Nom = "Chanel N°5",
                            NombreVues = 0,
                            Prix = 129.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 35,
                            CategorieId = 6,
                            DateAjout = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Eau de toilette fraîche et épicée pour homme, notes de bergamote et poivre",
                            ImageUrl = "/images/produits/sauvage.jpg",
                            Nom = "Dior Sauvage",
                            NombreVues = 0,
                            Prix = 89.99m,
                            Stock = 65
                        },
                        new
                        {
                            Id = 36,
                            CategorieId = 6,
                            DateAjout = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Parfum oriental gourmand pour femme, café et vanille",
                            ImageUrl = "/images/produits/blackopium.jpg",
                            Nom = "Black Opium YSL",
                            NombreVues = 0,
                            Prix = 99.99m,
                            Stock = 55
                        },
                        new
                        {
                            Id = 37,
                            CategorieId = 6,
                            DateAjout = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Eau de toilette fraîche marine pour homme, notes aquatiques",
                            ImageUrl = "/images/produits/acqua.jpg",
                            Nom = "Acqua di Gio",
                            NombreVues = 0,
                            Prix = 79.99m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 38,
                            CategorieId = 6,
                            DateAjout = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Eau de parfum florale gourmande, iris et patchouli",
                            ImageUrl = "/images/produits/lavieestbelle.jpg",
                            Nom = "La Vie Est Belle",
                            NombreVues = 0,
                            Prix = 109.99m,
                            Stock = 45
                        });
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.AttributCategorie", b =>
                {
                    b.HasOne("BoutiqueEnLigne.Models.Categorie", "Categorie")
                        .WithMany("AttributsDisponibles")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.AttributProduit", b =>
                {
                    b.HasOne("BoutiqueEnLigne.Models.Produit", "Produit")
                        .WithMany("Attributs")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Commande", b =>
                {
                    b.HasOne("BoutiqueEnLigne.Models.Utilisateur", "Utilisateur")
                        .WithMany("Commandes")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.LigneCommande", b =>
                {
                    b.HasOne("BoutiqueEnLigne.Models.Commande", "Commande")
                        .WithMany("LignesCommande")
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoutiqueEnLigne.Models.Produit", "Produit")
                        .WithMany("LignesCommande")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Panier", b =>
                {
                    b.HasOne("BoutiqueEnLigne.Models.Utilisateur", "Utilisateur")
                        .WithOne("Panier")
                        .HasForeignKey("BoutiqueEnLigne.Models.Panier", "UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.PanierItem", b =>
                {
                    b.HasOne("BoutiqueEnLigne.Models.Panier", "Panier")
                        .WithMany("Items")
                        .HasForeignKey("PanierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoutiqueEnLigne.Models.Produit", "Produit")
                        .WithMany("PaniersItems")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Panier");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Produit", b =>
                {
                    b.HasOne("BoutiqueEnLigne.Models.Categorie", "Categorie")
                        .WithMany("Produits")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Categorie", b =>
                {
                    b.Navigation("AttributsDisponibles");

                    b.Navigation("Produits");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Commande", b =>
                {
                    b.Navigation("LignesCommande");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Panier", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Produit", b =>
                {
                    b.Navigation("Attributs");

                    b.Navigation("LignesCommande");

                    b.Navigation("PaniersItems");
                });

            modelBuilder.Entity("BoutiqueEnLigne.Models.Utilisateur", b =>
                {
                    b.Navigation("Commandes");

                    b.Navigation("Panier")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
